<?xml version="1.0" encoding="utf-8"?><Database Name="HVCC_DEV" Class="HVCCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HVCCSERVER\SQLEXPRESS;Initial Catalog=HVCC;Integrated Security=True" SettingsObjectName="HVCC.Shell.Properties.Settings" SettingsPropertyName="HVCCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WaterMeterReadings" Member="WaterMeterReadings">
    <Type Name="WaterMeterReading">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeterReading" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReadingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Consumption" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Property_WaterMeterReading" Member="Property" ThisKey="PropertyID" OtherKey="PropertyID" Type="Property" IsForeignKey="true" />
    </Type>
    <UpdateFunction FunctionId="FunctionId1">
      <Argument Parameter="rowId" Member="RowID" />
      <Argument Parameter="propertyId" Member="PropertyID" />
      <Argument Parameter="meterReading" Member="MeterReading" />
      <Argument Parameter="consumption" Member="Consumption" />
      <Argument Parameter="readingDate" Member="ReadingDate" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId2">
      <Argument Parameter="rowId" Member="RowID" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.ApplicationDefaults" Member="ApplicationDefaults">
    <Type Name="ApplicationDefault">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.WellXProperty" Member="WellXProperties">
    <Type Name="WellXProperty">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WellNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="WaterWell_WellXProperty" Member="WaterWell" ThisKey="WellNumber" OtherKey="WellNumber" Type="WaterWell" IsForeignKey="true" />
      <Association Name="Property_WellXProperty" Member="Property" ThisKey="PropertyId" OtherKey="PropertyID" Type="Property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WaterWells" Member="WaterWells">
    <Type Name="WaterWell">
      <Column Name="WellNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServiceArea" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MeterUnits" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UnitMultiplier" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Association Name="WaterWell_WellXProperty" Member="WellXProperties" ThisKey="WellNumber" OtherKey="WellNumber" Type="WellXProperty" />
      <Association Name="WaterWell_WellMeterReading" Member="WellMeterReadings" ThisKey="WellNumber" OtherKey="WellNumber" Type="WellMeterReading" />
    </Type>
  </Table>
  <Table Name="dbo.WellMeterReadings" Member="WellMeterReadings">
    <Type Name="WellMeterReading">
      <Column Name="RowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WellNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeterReadingDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MeterReading" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MeterUnitOfMeasure" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ThroughputInGallons" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="EnteredBy" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Entered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="WaterWell_WellMeterReading" Member="WaterWell" ThisKey="WellNumber" OtherKey="WellNumber" Type="WaterWell" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId3">
      <Argument Parameter="wellNumber" Member="WellNumber" />
      <Argument Parameter="meterReadingDate" Member="MeterReadingDate" />
      <Argument Parameter="meterReading" Member="MeterReading" />
      <Argument Parameter="meterUnitOfMeasure" Member="MeterUnitOfMeasure" />
      <Argument Parameter="throughputInGallons" Member="ThroughputInGallons" />
      <Argument Parameter="rowID" Member="RowId" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.Relationships" Member="Relationships">
    <Type Name="Relationship">
      <Column Name="RelationshipID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RelationToOwner" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Owner_Relationship" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notes" Member="Notes">
    <Type Name="Note">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="EnteredBy" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Entered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Owner_Note" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId4">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="comment" Member="Comment" />
      <Argument Parameter="rowID" Member="RowID" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.OwnershipChanges" Member="OwnershipChanges">
    <Type Name="OwnershipChange">
      <Column Name="RowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewOwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewOwner" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PreviousOwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PreviousOwner" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId5">
      <Argument Parameter="propertyId" Member="PropertyID" />
      <Argument Parameter="previousOwnerID" Member="PreviousOwnerID" />
      <Argument Parameter="previousOwner" Member="PreviousOwner" />
      <Argument Parameter="newOwnerID" Member="NewOwnerID" />
      <Argument Parameter="newOwner" Member="NewOwner" />
      <Argument Parameter="rowID" Member="RowId" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.v_OwnerDetails" Member="v_OwnerDetails">
    <Type Name="v_OwnerDetail">
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MailTo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SecondaryPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IsSendByEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WaterShutoffs" Member="WaterShutoffs">
    <Type Name="WaterShutoff">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsWaterShutoff" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsMemberSuspended" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SuspensionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsLate30" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FirstNotificationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsLate60" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SecondNotificationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsLate90" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsShutoffNoticeIssued" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShutoffNoticeIssuedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsMemberRequestedHearing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HearingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsInCollections" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CollectionsDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsMeterLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsOnPaymentPlan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TermsOfPaymentPlan" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IsIntentToLien" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IntentToLienDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsLienFiled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LienFiledDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsResolved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ResolutionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Resolution" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Owner_WaterShutoff" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId6">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="isWaterShutoff" Member="IsWaterShutoff" />
      <Argument Parameter="isMemberSuspended" Member="IsMemberSuspended" />
      <Argument Parameter="suspensionDate" Member="SuspensionDate" />
      <Argument Parameter="isLate30" Member="IsLate30" />
      <Argument Parameter="firstNotificationDate" Member="FirstNotificationDate" />
      <Argument Parameter="isLate60" Member="IsLate60" />
      <Argument Parameter="secondNotificationDate" Member="SecondNotificationDate" />
      <Argument Parameter="isLate90" Member="IsLate90" />
      <Argument Parameter="isShutoffNoticeIssued" Member="IsShutoffNoticeIssued" />
      <Argument Parameter="shutoffNoticeIssuedDate" Member="ShutoffNoticeIssuedDate" />
      <Argument Parameter="isMemberRequestedHearing" Member="IsMemberRequestedHearing" />
      <Argument Parameter="hearingDate" Member="HearingDate" />
      <Argument Parameter="isInCollections" Member="IsInCollections" />
      <Argument Parameter="collectionsDate" Member="CollectionsDate" />
      <Argument Parameter="isMeterLocked" Member="IsMeterLocked" />
      <Argument Parameter="isOnPaymentPlan" Member="IsOnPaymentPlan" />
      <Argument Parameter="termsOfPaymentPlan" Member="TermsOfPaymentPlan" />
      <Argument Parameter="isIntentToLien" Member="IsIntentToLien" />
      <Argument Parameter="intentToLienDate" Member="IntentToLienDate" />
      <Argument Parameter="isLienFiled" Member="IsLienFiled" />
      <Argument Parameter="lienFiledDate" Member="LienFiledDate" />
      <Argument Parameter="isResolved" Member="IsResolved" />
      <Argument Parameter="resolutionDate" Member="ResolutionDate" />
      <Argument Parameter="resolution" Member="Resolution" />
      <Argument Parameter="rowID" Member="RowID" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId7">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="isWaterShutoff" Member="IsWaterShutoff" />
      <Argument Parameter="isMemberSuspended" Member="IsMemberSuspended" />
      <Argument Parameter="suspensionDate" Member="SuspensionDate" />
      <Argument Parameter="isLate30" Member="IsLate30" />
      <Argument Parameter="firstNotificationDate" Member="FirstNotificationDate" />
      <Argument Parameter="isLate60" Member="IsLate60" />
      <Argument Parameter="secondNotificationDate" Member="SecondNotificationDate" />
      <Argument Parameter="isLate90" Member="IsLate90" />
      <Argument Parameter="isShutoffNoticeIssued" Member="IsShutoffNoticeIssued" />
      <Argument Parameter="shutoffNoticeIssuedDate" Member="ShutoffNoticeIssuedDate" />
      <Argument Parameter="isMemberRequestedHearing" Member="IsMemberRequestedHearing" />
      <Argument Parameter="hearingDate" Member="HearingDate" />
      <Argument Parameter="isInCollections" Member="IsInCollections" />
      <Argument Parameter="collectionsDate" Member="CollectionsDate" />
      <Argument Parameter="isMeterLocked" Member="IsMeterLocked" />
      <Argument Parameter="isOnPaymentPlan" Member="IsOnPaymentPlan" />
      <Argument Parameter="termsOfPaymentPlan" Member="TermsOfPaymentPlan" />
      <Argument Parameter="isIntentToLien" Member="IsIntentToLien" />
      <Argument Parameter="intentToLienDate" Member="IntentToLienDate" />
      <Argument Parameter="isLienFiled" Member="IsLienFiled" />
      <Argument Parameter="lienFiledDate" Member="LienFiledDate" />
      <Argument Parameter="isResolved" Member="IsResolved" />
      <Argument Parameter="resolutionDate" Member="ResolutionDate" />
      <Argument Parameter="resolution" Member="Resolution" />
    </UpdateFunction>
  </Table>
  <Table Name="dbo.v_WaterShutoffs" Member="v_WaterShutoffs">
    <Type Name="v_WaterShutoff">
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SuspensionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsMeterLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLate30" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLate60" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLate90" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsOnPaymentPlan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsInCollections" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsIntentToLien" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLienFiled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FirstNotificationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SecondNotificationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ShutoffNoticeIssuedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LienFiledDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsWaterShutoff" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsMemberSuspended" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsShutoffNoticeIssued" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsMemberRequestedHearing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HearingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CollectionsDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TermsOfPaymentPlan" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IntentToLienDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsResolved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ResolutionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Resolution" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="MailTo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationPermissions" Member="ApplicationPermissions">
    <Type Name="ApplicationPermission">
      <Column Name="RowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="RoleIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CanViewProperty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanEditProperty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanViewOwner" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanEditOwner" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanViewOwnerNotes" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanEditOwnerNotes" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanAddRelationship" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanEditRelationship" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanCheckIn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanViewWater" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanEditWater" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanImport" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanExport" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanPrint" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanViewAdministration" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Seasons" Member="Seasons">
    <Type Name="Season">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimePeriod" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsCurrent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsNext" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnnualDues" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CartFee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Assessment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AssessmentAmount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="IsDuesApplied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLate30Applied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLate60Applied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLate90Applied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_ActiveRelationships" Member="v_ActiveRelationships">
    <Type Name="v_ActiveRelationship">
      <Column Name="RelationshipID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RelationToOwner" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MailTo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCurrentOwner" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Properties" Member="Properties">
    <Type Name="Property">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Section" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Block" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubLot" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Parcel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhysicalAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CommonNotes" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="IsAssessment" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MeterNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WaterSystemNotes" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Property_WaterMeterReading" Member="WaterMeterReadings" ThisKey="PropertyID" OtherKey="PropertyID" Type="WaterMeterReading" />
      <Association Name="Property_WellXProperty" Member="WellXProperties" ThisKey="PropertyID" OtherKey="PropertyId" Type="WellXProperty" />
      <Association Name="Owner_Property" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
    <UpdateFunction FunctionId="FunctionId8">
      <Argument Parameter="propertyId" Member="PropertyID" />
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="customer" Member="Customer" />
      <Argument Parameter="section" Member="Section" />
      <Argument Parameter="block" Member="Block" />
      <Argument Parameter="lot" Member="Lot" />
      <Argument Parameter="subLot" Member="SubLot" />
      <Argument Parameter="balance" Member="Balance" />
      <Argument Parameter="parcel" Member="Parcel" />
      <Argument Parameter="physicalAddress" Member="PhysicalAddress" />
      <Argument Parameter="status" Member="Status" />
      <Argument Parameter="commonNotes" Member="CommonNotes" />
      <Argument Parameter="isAssessment" Member="IsAssessment" />
      <Argument Parameter="meterNumber" Member="MeterNumber" />
      <Argument Parameter="waterSystemNotes" Member="WaterSystemNotes" />
    </UpdateFunction>
  </Table>
  <Table Name="dbo.v_PropertyDetails" Member="v_PropertyDetails">
    <Type Name="v_PropertyDetail">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Section" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Block" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubLot" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Parcel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhysicalAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CommonNotes" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="IsAssessment" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MeterNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WaterSystemNotes" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="OwnerBalance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MailTo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IsSendByEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SecondaryPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GolfCarts" Member="GolfCarts">
    <Type Name="GolfCart">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quanity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPaid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsReceived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReceivedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="Owner_GolfCart" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId9">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="customer" Member="Customer" />
      <Argument Parameter="year" Member="Year" />
      <Argument Parameter="quanity" Member="Quanity" />
      <Argument Parameter="isPaid" Member="IsPaid" />
      <Argument Parameter="paymentDate" Member="PaymentDate" />
      <Argument Parameter="rowID" Member="RowID" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId10">
      <Argument Parameter="rowID" Member="RowID" />
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="customer" Member="Customer" />
      <Argument Parameter="year" Member="Year" />
      <Argument Parameter="quanity" Member="Quanity" />
      <Argument Parameter="isPaid" Member="IsPaid" />
      <Argument Parameter="paymentDate" Member="PaymentDate" />
      <Argument Parameter="isReceived" Member="IsReceived" />
      <Argument Parameter="receivedDate" Member="ReceivedDate" />
    </UpdateFunction>
  </Table>
  <Table Name="dbo.v_ChangeOfOwnership" Member="v_ChangeOfOwnerships">
    <Type Name="v_ChangeOfOwnership">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NewOwner" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="NewOwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PreviousOwner" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PreviousOwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FacilityUsages" Member="FacilityUsages">
    <Type Name="FacilityUsage">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelationshipId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GolfRoundsMember" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GolfRoundsGuest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PoolMember" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PoolGuest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId11">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="relationshipId" Member="RelationshipId" />
      <Argument Parameter="golfRoundsMember" Member="GolfRoundsMember" />
      <Argument Parameter="golfRoundsGuest" Member="GolfRoundsGuest" />
      <Argument Parameter="poolMember" Member="PoolMember" />
      <Argument Parameter="poolGuest" Member="PoolGuest" />
      <Argument Parameter="rowID" Member="RowID" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.FinancialTransactions" Member="FinancialTransactions">
    <Type Name="FinancialTransaction">
      <Column Name="RowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FiscalYear" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CreditAmount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DebitAmount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TransactionMethod" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionAppliesTo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CheckNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastMOdifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Owner_FinancialTransaction" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId12">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="fiscalYEar" Member="FiscalYear" />
      <Argument Parameter="balance" Member="Balance" />
      <Argument Parameter="creditAmount" Member="CreditAmount" />
      <Argument Parameter="debitAmount" Member="DebitAmount" />
      <Argument Parameter="transactionDate" Member="TransactionDate" />
      <Argument Parameter="transactionMethod" Member="TransactionMethod" />
      <Argument Parameter="transactionAppliesTo" Member="TransactionAppliesTo" />
      <Argument Parameter="comment" Member="Comment" />
      <Argument Parameter="checkNumber" Member="CheckNumber" />
      <Argument Parameter="receiptNumber" Member="ReceiptNumber" />
      <Argument Parameter="rowID" Member="RowId" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId13">
      <Argument Parameter="rowId" Member="RowId" />
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="fiscalYear" Member="FiscalYear" />
      <Argument Parameter="balance" Member="Balance" />
      <Argument Parameter="creditAmount" Member="CreditAmount" />
      <Argument Parameter="debitAmount" Member="DebitAmount" />
      <Argument Parameter="transactionDate" Member="TransactionDate" />
      <Argument Parameter="transactionMethod" Member="TransactionMethod" />
      <Argument Parameter="transactionAppliesTo" Member="TransactionAppliesTo" />
      <Argument Parameter="comment" Member="Comment" />
      <Argument Parameter="checkNumber" Member="CheckNumber" />
      <Argument Parameter="receiptNumber" Member="ReceiptNumber" />
    </UpdateFunction>
  </Table>
  <Table Name="dbo.Owners" Member="Owners">
    <Type Name="Owner">
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MailTo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IsSendByEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SecondaryPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsCurrentOwner" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPrimaryRes" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsWeekend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSeasonal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsRental" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsRVlot" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsEmptyLot" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Owner_Relationship" Member="Relationships" ThisKey="OwnerID" OtherKey="OwnerID" Type="Relationship" />
      <Association Name="Owner_Note" Member="Notes" ThisKey="OwnerID" OtherKey="OwnerID" Type="Note" />
      <Association Name="Owner_WaterShutoff" Member="WaterShutoffs" ThisKey="OwnerID" OtherKey="OwnerID" Type="WaterShutoff" />
      <Association Name="Owner_Property" Member="Properties" ThisKey="OwnerID" OtherKey="OwnerID" Type="Property" />
      <Association Name="Owner_GolfCart" Member="GolfCarts" ThisKey="OwnerID" OtherKey="OwnerID" Type="GolfCart" />
      <Association Name="Owner_FinancialTransaction" Member="FinancialTransactions" ThisKey="OwnerID" OtherKey="OwnerID" Type="FinancialTransaction" />
      <Association Name="Owner_Late90Day" Member="Late90Days" ThisKey="OwnerID" OtherKey="OwnerID" Type="Late90Day" />
      <Association Name="Owner_Late60Day" Member="Late60Days" ThisKey="OwnerID" OtherKey="OwnerID" Type="Late60Day" />
      <Association Name="Owner_Late30Day" Member="Late30Days" ThisKey="OwnerID" OtherKey="OwnerID" Type="Late30Day" />
    </Type>
    <InsertFunction FunctionId="FunctionId14">
      <Argument Parameter="customer" Member="Customer" />
      <Argument Parameter="mailTo" Member="MailTo" />
      <Argument Parameter="address" Member="Address" />
      <Argument Parameter="address2" Member="Address2" />
      <Argument Parameter="city" Member="City" />
      <Argument Parameter="state" Member="State" />
      <Argument Parameter="zip" Member="Zip" />
      <Argument Parameter="primaryPhone" Member="PrimaryPhone" />
      <Argument Parameter="secondaryPhone" Member="SecondaryPhone" />
      <Argument Parameter="emailAddress" Member="EmailAddress" />
      <Argument Parameter="isSendByEmail" Member="IsSendByEmail" />
      <Argument Parameter="isCurrentOwner" Member="IsCurrentOwner" />
      <Argument Parameter="isPrimaryRes" Member="IsPrimaryRes" />
      <Argument Parameter="isWeekend" Member="IsWeekend" />
      <Argument Parameter="isSeasonal" Member="IsSeasonal" />
      <Argument Parameter="isRental" Member="IsRental" />
      <Argument Parameter="isRVlot" Member="IsRVlot" />
      <Argument Parameter="isEmptyLot" Member="IsEmptyLot" />
      <Argument Parameter="ownerID" Member="OwnerID" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId15">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="customer" Member="Customer" />
      <Argument Parameter="mailTo" Member="MailTo" />
      <Argument Parameter="address" Member="Address" />
      <Argument Parameter="address2" Member="Address2" />
      <Argument Parameter="city" Member="City" />
      <Argument Parameter="state" Member="State" />
      <Argument Parameter="zip" Member="Zip" />
      <Argument Parameter="primaryPhone" Member="PrimaryPhone" />
      <Argument Parameter="secondaryPhone" Member="SecondaryPhone" />
      <Argument Parameter="emailAddress" Member="EmailAddress" />
      <Argument Parameter="isSendByEmail" Member="IsSendByEmail" />
      <Argument Parameter="isCurrentOwner" Member="IsCurrentOwner" />
      <Argument Parameter="isPrimaryRes" Member="IsPrimaryRes" />
      <Argument Parameter="isWeekend" Member="IsWeekend" />
      <Argument Parameter="isSeasonal" Member="IsSeasonal" />
      <Argument Parameter="isRental" Member="IsRental" />
      <Argument Parameter="isRVlot" Member="IsRVlot" />
      <Argument Parameter="isEmptyLot" Member="IsEmptyLot" />
    </UpdateFunction>
  </Table>
  <Table Name="dbo.Late90Days" Member="Late90Days">
    <Type Name="Late90Day">
      <Column Name="RowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Season" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Owner_Late90Day" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId16">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="season" Member="Season" />
      <Argument Parameter="rowID" Member="RowId" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.Late60Days" Member="Late60Days">
    <Type Name="Late60Day">
      <Column Name="RowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Season" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Owner_Late60Day" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId17">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="season" Member="Season" />
      <Argument Parameter="rowID" Member="RowId" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.Late30Days" Member="Late30Days">
    <Type Name="Late30Day">
      <Column Name="RowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MailTo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Season" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Owner_Late30Day" Member="Owner" ThisKey="OwnerID" OtherKey="OwnerID" Type="Owner" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId18">
      <Argument Parameter="ownerID" Member="OwnerID" />
      <Argument Parameter="mailTo" Member="MailTo" />
      <Argument Parameter="season" Member="Season" />
      <Argument Parameter="rowID" Member="RowId" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.v_WaterMeterReadings" Member="v_WaterMeterReadings">
    <Type Name="v_WaterMeterReading">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhysicalAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReadingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MeterReading" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Consumption" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.usp_GetPropertyById" Method="usp_GetPropertyById">
    <Parameter Name="PropertyID" Parameter="propertyID" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_GetPropertyByIdResult">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Section" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Block" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubLot" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BillTo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="IsInGoodStanding" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Parcel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhysicalAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="OwnerLName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OwnerFName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OwnerAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OwnerAddress2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OwnerCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OwnerState" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="OwnerZip" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OwnerPrimaryPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OwnerSecondaryPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OwnerEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MeterNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyNotes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="WaterSystemNotes" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Id="FunctionId2" Name="dbo.usp_DeleteWaterMeterReading" Method="usp_DeleteWaterMeterReading">
    <Parameter Name="RowId" Parameter="rowId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId1" Name="dbo.usp_UpdateWaterMeterReading" Method="usp_UpdateWaterMeterReading">
    <Parameter Name="RowId" Parameter="rowId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PropertyId" Parameter="propertyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="MeterReading" Parameter="meterReading" Type="System.Int32" DbType="Int" />
    <Parameter Name="Consumption" Parameter="consumption" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReadingDate" Parameter="readingDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_DeleteFacilityUsage" Method="usp_DeleteFacilityUsage">
    <Parameter Name="RowId" Parameter="rowId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_UdateFacilityUsage" Method="usp_UdateFacilityUsage">
    <Parameter Name="PropertyId" Parameter="propertyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="GolfRoundsMember" Parameter="golfRoundsMember" Type="System.Int32" DbType="Int" />
    <Parameter Name="GolfRoundsGuest" Parameter="golfRoundsGuest" Type="System.Int32" DbType="Int" />
    <Parameter Name="PoolMember" Parameter="poolMember" Type="System.Int32" DbType="Int" />
    <Parameter Name="PoolGuest" Parameter="poolGuest" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_DeleteNote" Method="usp_DeleteNote">
    <Parameter Name="RowId" Parameter="rowId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fn_IsMember" Method="fn_IsMember" IsComposable="true">
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.usp_GetFacilityUsageForDate" Method="usp_GetFacilityUsageForDate">
    <Parameter Name="RelationshipID" Parameter="relationshipID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Golf" Parameter="golf" Type="System.Int32" DbType="Int" />
    <Parameter Name="Pool" Parameter="pool" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date1" Parameter="date1" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Date2" Parameter="date2" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="usp_GetFacilityUsageForDateResult">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelationshipId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GolfRoundsMember" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GolfRoundsGuest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PoolMember" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PoolGuest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Id="FunctionId3" Name="dbo.usp_InsertWellMeterReading" Method="usp_InsertWellMeterReading">
    <Parameter Name="WellNumber" Parameter="wellNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="MeterReadingDate" Parameter="meterReadingDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MeterReading" Parameter="meterReading" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MeterUnitOfMeasure" Parameter="meterUnitOfMeasure" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ThroughputInGallons" Parameter="throughputInGallons" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_DeleteRelationship" Method="usp_DeleteRelationship">
    <Parameter Name="RelationshipId" Parameter="relationshipId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_InsertProperty" Method="usp_InsertProperty">
    <Parameter Name="Customer" Parameter="customer" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Section" Parameter="section" Type="System.Int32" DbType="Int" />
    <Parameter Name="Block" Parameter="block" Type="System.Int32" DbType="Int" />
    <Parameter Name="Lot" Parameter="lot" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubLot" Parameter="subLot" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="BillTo" Parameter="billTo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(19,4)" />
    <Parameter Name="IsInGoodStanding" Parameter="isInGoodStanding" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Parcel" Parameter="parcel" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PhysicalAddress" Parameter="physicalAddress" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MeterNumber" Parameter="meterNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="WaterSystemNotes" Parameter="waterSystemNotes" Type="System.String" DbType="VarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_DeleteRelationshipXOwner" Method="usp_DeleteRelationshipXOwner">
    <Parameter Name="RelationshipId" Parameter="relationshipId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_InsertRelationship" Method="usp_InsertRelationship">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FName" Parameter="fName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LName" Parameter="lName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RelationToOwner" Parameter="relationToOwner" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Photo" Parameter="photo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="RelationshipId" Parameter="relationshipId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_UdateRelationship" Method="usp_UdateRelationship">
    <Parameter Name="RelationshipId" Parameter="relationshipId" Type="System.Int32" DbType="Int" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FName" Parameter="fName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LName" Parameter="lName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RelationToOwner" Parameter="relationToOwner" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Photo" Parameter="photo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_UdateNote" Method="usp_UdateNote">
    <Parameter Name="PropertyId" Parameter="propertyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId4" Name="dbo.usp_InsertNote" Method="usp_InsertNote">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId5" Name="dbo.usp_InsertOwnershipChange" Method="usp_InsertOwnershipChange">
    <Parameter Name="PropertyId" Parameter="propertyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PreviousOwnerID" Parameter="previousOwnerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PreviousOwner" Parameter="previousOwner" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="NewOwnerID" Parameter="newOwnerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewOwner" Parameter="newOwner" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId6" Name="dbo.usp_InsertWaterShutoff" Method="usp_InsertWaterShutoff">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsWaterShutoff" Parameter="isWaterShutoff" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsMemberSuspended" Parameter="isMemberSuspended" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SuspensionDate" Parameter="suspensionDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsLate30" Parameter="isLate30" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FirstNotificationDate" Parameter="firstNotificationDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsLate60" Parameter="isLate60" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SecondNotificationDate" Parameter="secondNotificationDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsLate90" Parameter="isLate90" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsShutoffNoticeIssued" Parameter="isShutoffNoticeIssued" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ShutoffNoticeIssuedDate" Parameter="shutoffNoticeIssuedDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsMemberRequestedHearing" Parameter="isMemberRequestedHearing" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="HearingDate" Parameter="hearingDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsInCollections" Parameter="isInCollections" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CollectionsDate" Parameter="collectionsDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsMeterLocked" Parameter="isMeterLocked" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsOnPaymentPlan" Parameter="isOnPaymentPlan" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TermsOfPaymentPlan" Parameter="termsOfPaymentPlan" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="IsIntentToLien" Parameter="isIntentToLien" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IntentToLienDate" Parameter="intentToLienDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsLienFiled" Parameter="isLienFiled" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LienFiledDate" Parameter="lienFiledDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsResolved" Parameter="isResolved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ResolutionDate" Parameter="resolutionDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Resolution" Parameter="resolution" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId7" Name="dbo.usp_UpdateWaterShutoff" Method="usp_UpdateWaterShutoff">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsWaterShutoff" Parameter="isWaterShutoff" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsMemberSuspended" Parameter="isMemberSuspended" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SuspensionDate" Parameter="suspensionDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsLate30" Parameter="isLate30" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FirstNotificationDate" Parameter="firstNotificationDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsLate60" Parameter="isLate60" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SecondNotificationDate" Parameter="secondNotificationDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsLate90" Parameter="isLate90" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsShutoffNoticeIssued" Parameter="isShutoffNoticeIssued" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ShutoffNoticeIssuedDate" Parameter="shutoffNoticeIssuedDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsMemberRequestedHearing" Parameter="isMemberRequestedHearing" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="HearingDate" Parameter="hearingDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsInCollections" Parameter="isInCollections" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CollectionsDate" Parameter="collectionsDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsMeterLocked" Parameter="isMeterLocked" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsOnPaymentPlan" Parameter="isOnPaymentPlan" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TermsOfPaymentPlan" Parameter="termsOfPaymentPlan" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="IsIntentToLien" Parameter="isIntentToLien" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IntentToLienDate" Parameter="intentToLienDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsLienFiled" Parameter="isLienFiled" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LienFiledDate" Parameter="lienFiledDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsResolved" Parameter="isResolved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ResolutionDate" Parameter="resolutionDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Resolution" Parameter="resolution" Type="System.String" DbType="VarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId8" Name="dbo.usp_UpdateProperty" Method="usp_UpdateProperty">
    <Parameter Name="PropertyId" Parameter="propertyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Customer" Parameter="customer" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Section" Parameter="section" Type="System.Int32" DbType="Int" />
    <Parameter Name="Block" Parameter="block" Type="System.Int32" DbType="Int" />
    <Parameter Name="Lot" Parameter="lot" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubLot" Parameter="subLot" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(19,4)" />
    <Parameter Name="Parcel" Parameter="parcel" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PhysicalAddress" Parameter="physicalAddress" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CommonNotes" Parameter="commonNotes" Type="System.String" DbType="VarChar(400)" />
    <Parameter Name="IsAssessment" Parameter="isAssessment" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MeterNumber" Parameter="meterNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="WaterSystemNotes" Parameter="waterSystemNotes" Type="System.String" DbType="VarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_GetInvoiceForOwner" Method="usp_GetInvoiceForOwner">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_GetInvoiceForOwnerResult">
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Customer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MailTo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Item" Type="System.String" DbType="VarChar(52) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="IsAssessment" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Assessment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AssessmentAmount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Id="FunctionId9" Name="dbo.usp_InsertGolfCart" Method="usp_InsertGolfCart">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Customer" Parameter="customer" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Year" Parameter="year" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Quanity" Parameter="quanity" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsPaid" Parameter="isPaid" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PaymentDate" Parameter="paymentDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId10" Name="dbo.usp_UdateGolfCart" Method="usp_UdateGolfCart">
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Customer" Parameter="customer" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Year" Parameter="year" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Quanity" Parameter="quanity" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsPaid" Parameter="isPaid" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PaymentDate" Parameter="paymentDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsReceived" Parameter="isReceived" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ReceivedDate" Parameter="receivedDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId11" Name="dbo.usp_InsertFacilityUsage" Method="usp_InsertFacilityUsage">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RelationshipId" Parameter="relationshipId" Type="System.Int32" DbType="Int" />
    <Parameter Name="GolfRoundsMember" Parameter="golfRoundsMember" Type="System.Int32" DbType="Int" />
    <Parameter Name="GolfRoundsGuest" Parameter="golfRoundsGuest" Type="System.Int32" DbType="Int" />
    <Parameter Name="PoolMember" Parameter="poolMember" Type="System.Int32" DbType="Int" />
    <Parameter Name="PoolGuest" Parameter="poolGuest" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId12" Name="dbo.usp_InsertFinancialTransaction" Method="usp_InsertFinancialTransaction">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FiscalYEar" Parameter="fiscalYEar" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Money" />
    <Parameter Name="CreditAmount" Parameter="creditAmount" Type="System.Decimal" DbType="Money" />
    <Parameter Name="DebitAmount" Parameter="debitAmount" Type="System.Decimal" DbType="Money" />
    <Parameter Name="TransactionDate" Parameter="transactionDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TransactionMethod" Parameter="transactionMethod" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TransactionAppliesTo" Parameter="transactionAppliesTo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CheckNumber" Parameter="checkNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ReceiptNumber" Parameter="receiptNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId13" Name="dbo.usp_UpdateFinancialTransaction" Method="usp_UpdateFinancialTransaction">
    <Parameter Name="RowId" Parameter="rowId" Type="System.Int32" DbType="Int" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FiscalYear" Parameter="fiscalYear" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Money" />
    <Parameter Name="CreditAmount" Parameter="creditAmount" Type="System.Decimal" DbType="Money" />
    <Parameter Name="DebitAmount" Parameter="debitAmount" Type="System.Decimal" DbType="Money" />
    <Parameter Name="TransactionDate" Parameter="transactionDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TransactionMethod" Parameter="transactionMethod" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TransactionAppliesTo" Parameter="transactionAppliesTo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CheckNumber" Parameter="checkNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ReceiptNumber" Parameter="receiptNumber" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId14" Name="dbo.usp_InsertOwner" Method="usp_InsertOwner">
    <Parameter Name="Customer" Parameter="customer" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MailTo" Parameter="mailTo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PrimaryPhone" Parameter="primaryPhone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SecondaryPhone" Parameter="secondaryPhone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="EmailAddress" Parameter="emailAddress" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="IsSendByEmail" Parameter="isSendByEmail" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsCurrentOwner" Parameter="isCurrentOwner" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsPrimaryRes" Parameter="isPrimaryRes" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsWeekend" Parameter="isWeekend" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsSeasonal" Parameter="isSeasonal" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsRental" Parameter="isRental" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsRVlot" Parameter="isRVlot" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsEmptyLot" Parameter="isEmptyLot" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId16" Name="dbo.usp_InsertLate90" Method="usp_InsertLate90">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Season" Parameter="season" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId17" Name="dbo.usp_InsertLate60" Method="usp_InsertLate60">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Season" Parameter="season" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId18" Name="dbo.usp_InsertLate30" Method="usp_InsertLate30">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MailTo" Parameter="mailTo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Season" Parameter="season" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="RowID" Parameter="rowID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId15" Name="dbo.usp_UpdateOwner" Method="usp_UpdateOwner">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Customer" Parameter="customer" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MailTo" Parameter="mailTo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PrimaryPhone" Parameter="primaryPhone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SecondaryPhone" Parameter="secondaryPhone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="EmailAddress" Parameter="emailAddress" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="IsSendByEmail" Parameter="isSendByEmail" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsCurrentOwner" Parameter="isCurrentOwner" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsPrimaryRes" Parameter="isPrimaryRes" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsWeekend" Parameter="isWeekend" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsSeasonal" Parameter="isSeasonal" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsRental" Parameter="isRental" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsRVlot" Parameter="isRVlot" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsEmptyLot" Parameter="isEmptyLot" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
</Database>